# Generated by Django 2.2.10 on 2024-03-04 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_auto_20240227_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 1, 59, 2, 308613, tzinfo=utc)),
        ),
    ]
