# Generated by Django 2.2.10 on 2024-03-13 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_auto_20240304_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20, verbose_name='提供者'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 6, 49, 55, 74820, tzinfo=utc)),
        ),
    ]
