# Generated by Django 2.2.10 on 2024-03-17 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_auto_20240313_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 12, 59, 6, 469989, tzinfo=utc)),
        ),
    ]
