# Generated by Django 2.2.10 on 2024-03-17 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_auto_20240317_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 13, 20, 32, 22605, tzinfo=utc)),
        ),
    ]
