# Generated by Django 2.2.10 on 2024-03-18 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_auto_20240317_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20, verbose_name='提供者1'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 3, 58, 38, 882191, tzinfo=utc)),
        ),
    ]
