# Generated by Django 2.2.10 on 2024-03-21 00:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_auto_20240318_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20, verbose_name='提供者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelf_number',
            field=models.CharField(default='0001', max_length=10, verbose_name='物品架编号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='book.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='物品描述'),
        ),
        migrations.AlterField(
            model_name='book',
            name='floor_number',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd')], default=1, verbose_name='楼层编号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher', to='book.Publisher', verbose_name='提供者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, '借出'), (1, '在库里')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='物品名称'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 0, 36, 26, 502663, tzinfo=utc), verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='open_or_close',
            field=models.IntegerField(choices=[(0, '开放'), (1, '关闭')], default=0),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='start_day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='租借开始时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y%m%d/', verbose_name='个人头像图片'),
        ),
    ]
