# Generated by Django 2.2.10 on 2024-03-23 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_auto_20240321_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='floor_number',
            field=models.IntegerField(choices=[(1, '一楼'), (2, '二楼'), (3, '三楼')], default=1, verbose_name='楼层编号'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 8, 49, 49, 704475, tzinfo=utc), verbose_name='归还时间'),
        ),
    ]
