# Generated by Django 2.2.10 on 2024-03-26 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_auto_20240323_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 14, 4, 58, 490496, tzinfo=utc), verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='open_or_close',
            field=models.IntegerField(choices=[(0, '正在借'), (1, '已入库')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(default=20, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='会员名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='电话号码'),
        ),
    ]
